version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: alvaro
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: